### ISSUE TITLE
travis.ci or i'm leaving

### ISSUE THREAD

**Issue by BlaisinX** [HardWare68/CollabDiscordBot#4] opened 2021-03-29 12:15 UTC

**Comment by HardWare68** [comment] 2021-03-29 12:16
we dont *need* Travis.ci though

**Comment by BlaisinX** [comment] 2021-03-29 12:18
you know you want travis.ci integration

**Comment by HardWare68** [comment] 2021-03-29 12:19
*sigh*

**Comment by BlaisinX** [comment] 2021-03-29 12:19
can't wait to run checks on master

**Comment by BlaisinX** [comment] 2021-03-29 12:21
this is very poggers

**Comment by HardWare68** [comment] 2021-03-29 12:32
im reopening this just to ask:
are you happy? are you happy now that there is travis.ci integration? is this what you wanted? you wanted the travis.ci servers to labour tirelessly on the piece of garbage you call your code? your code is a disgrace. it's horrific. and you want travis.ci to look at it for the rest of time?

**Comment by BlaisinX** [comment] 2021-03-29 12:35
Yes.

**Comment by HardWare68** [comment] 2021-03-29 12:37
Let me get this straight:
You're laughing. A travis.ci server has ran your code tirelessly, and you're laughing.

**Comment by BlaisinX** [comment] 2021-03-29 12:37
Yes.

**Comment by HardWare68** [comment] 2021-03-29 12:40
Look what happened because of what you did, what it led to! There are riots at the travis.ci headquarters! Two servers are in critical condition and you're laughing. You're laughing. Someone was killed today because of what you did.

**Comment by BlaisinX** [comment] 2021-03-29 12:40
Okay, and?

**Comment by HardWare68** [comment] 2021-03-29 12:42
no that wasn't how you were suppose dto respond 🤬 🤬 🤬 
have ayou eevne wathced Joker??>????

**Comment by BlaisinX** [comment] 2021-03-29 12:42
No. :le:

**Comment by HardWare68** [comment] 2021-03-29 12:44
You"re supposed to Say "How about aniotheor joke @Hardware69?" and them d p that kple tjat Joquaion Pheoninx is known for 🤬 🤬 🤬

**Comment by BlaisinX** [comment] 2021-03-29 12:44
okay
How about aniotheor joke @hardware69?

**Comment by HardWare68** [comment] 2021-03-29 12:46
U rtgubj qw;cw gS WBIYF G ID TIYE HIJWA, @N;laisinX

**Comment by BlaisinX** [comment] 2021-03-29 12:47
Nick McCann

**Comment by HardWare68** [comment] 2021-03-29 12:49
Here comes the money! (Money talks!)
Here comes the money!
Money, money, money, money, money, money, money, money, money (Dolla dolla, dolla dolla)

**Comment by BlaisinX** [comment] 2021-03-29 12:50
`if(money){profit};`

**Comment by HardWare68** [comment] 2021-03-29 12:52
`for money in range(money):
    profit()`

**Comment by BlaisinX** [comment] 2021-03-29 13:00
`do(yourMom);`

**Comment by HardWare68** [comment] 2021-03-29 13:02
Duplicate of #
Duplicate of 
Duplicate of 
Duplicate of ##1
Duplicate of ##1

**Closed as completed** 2021-03-30 12:07 UTC
Labels: enhancement
